splitwise/dashboard/urls.py
from django.urls import path
from django.conf.urls.static import static
from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.conf.urls import include

app_name = 'dashboard'
urlpatterns = [
    path('', views.index, name='index'),
    path('register', views.register, name='register'),
    path("logout", views.logout_request, name="logout"),
    path("login", views.login_request, name="login"),
    path('dashboard',views.personal_page,name='dashboard'),
    path('friends/<int:friend_id>',views.friend_page,name='friend'),
    path('groups',views.my_group,name='all_groups'),
    path('group/<int:group_id>',views.group_page,name='group'),
    path('addfriend/<str:name>',views.addfriend,name='fadd'),
    path('settings',views.userprofile,name='user_profile'),
    path('changepic',views.update_pic,name='update-pic'),
    path('settleup/<int:friend_id>',views.settleUp,name='settleup'),
    path('remove/<int:group_id>',views.delete,name="delete"),
    path('leave/<int:group_id>',views.leave,name='leave'),
    path('password', views.change_password, name='changePassword'),
    path('insights', views.insights, name='insights'),
    path('pdf_view', views.pdf_view, name='pdf_view'),
    path('balance/<int:group_id>',views.balance,name='balance'),
    path('activity',views.activity,name='activity'),
    path('excel',views.some_view,name='xlview'),
]

splitwise/splitwise/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from . import views

urlpatterns = [
	path('',include('dashboard.urls')),
    path('admin/', admin.site.urls),
    path('accounts/login',views.redirect_dashboard,name='updatepass'),
    path('accounts/profile/',views.redirect_dash,name='dash'),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

splitwise/dashboard/models.py
from django.db import models
from django.contrib.auth.models import User as Duser
from django.db.models.signals import post_save
from django.dispatch import receiver
from django import forms
from django.forms import ModelForm

# Create your models here.
class User(models.Model):
	user_name=models.CharField(max_length=50)
	email=models.EmailField(max_length=50, blank = True)
	friends = models.ManyToManyField("self",blank=True)
	dp=models.ImageField(upload_to='profile_pic',default='profile_pic/default.png')
	def __str__(self):
		return self.user_name
#class Friends(models.Model):
#	friend1=models.ForeignKey(User,on_delete=models.CASCADE,related_name='User 1')
#	friend2=models.ForeignKey(User,on_delete=models.CASCADE,related_name='User 2')
#	class Meta:
#		unique_together=(('friend1','friend2'),)

class Profile(models.Model):
	user = models.OneToOneField(Duser, on_delete=models.CASCADE)
	bio = models.TextField(max_length=500, blank=True)
	image = models.ImageField(max_length=100,blank=True)
	location = models.CharField(max_length=30, blank=True)
	#birth_date = models.DateField(null=True, blank=True)

class Group(models.Model):
	group_name=models.CharField(max_length=20)
	group_id=models.IntegerField(default=0)
	users=models.ManyToManyField(User)
	def __str__(self):
		return self.group_name


class Transaction(models.Model):
	title=models.CharField(max_length=140)
	trans_type=models.CharField(max_length=10)
	date=models.DateTimeField()
	group=models.ForeignKey(Group,on_delete=models.CASCADE,default=1)
	participants=models.ManyToManyField(User)
	comments=models.CharField(max_length=1000, blank=True)
	def __str__(self):
		return self.title

class TransactionDetail(models.Model):
	trans=models.ForeignKey(Transaction,on_delete=models.CASCADE)
	creditor=models.ForeignKey(User,on_delete=models.CASCADE,related_name="transaction_creditor")
	debitor=models.ForeignKey(User,on_delete=models.CASCADE,related_name="transaction_debitor")
	lent=models.FloatField()
	class Meta:
		unique_together=(('trans','creditor','debitor'),)



class NewGroupForm(forms.ModelForm):
	def __init__(self,*args,**kwargs): # initializing your form in other words loading it
		user_id=kwargs.pop('user_id')
		super(NewGroupForm, self).__init__(*args, **kwargs)
		user = User.objects.get(pk=user_id) # taking user_id out of the querylist
		self.fields['users'] = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple(), queryset=user.friends.all())
	class Meta:
		model=Group
		fields = ['group_name', 'users']

class DateRangeForm(forms.Form):
	Start_Date=forms.DateTimeField(widget=forms.SelectDateWidget())
	End_Date=forms.DateTimeField(widget=forms.SelectDateWidget())

class UpdatedpForm(forms.Form):
	file=forms.FileField()
	#class Meta:
	#	model=User
	#	fields=['dp']

class UploadFileForm(forms.Form):
    file = forms.ImageField()

splitwise/dashboard/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm,  AuthenticationForm
from django.contrib.auth import logout, authenticate, login
from django.contrib import messages
from django.contrib.auth.models import User
from django.db.models import Q

from .forms import TransactionForm, TransactionDetailForm, TransactionParticipantsForm, RegisterForm, ModifyTransactionForm, GroupSettleForm


from .models import User as myUser, Group as myGroup, Transaction, TransactionDetail, NewGroupForm, UpdatedpForm, UploadFileForm, DateRangeForm

import logging
import datetime
#from datetime import datetime
import pdb
import csv
LOG_FILENAME = 'views.log'
logging.basicConfig(filename=LOG_FILENAME,level=logging.DEBUG)

transFormType=1
participants_list=[]
title="the transaction"
trans_type="Others"
date=None
group=None
transaction=None

from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
from django.db.models import Q
from datetime import date

today = date.today()

# Create your views here.
def index(request):
	if request.user.is_authenticated:
		return redirect("dashboard:dashboard");
	else:
		return redirect("dashboard:login");

def register(request):
	form = RegisterForm(request.POST or None)
	if request.method == "POST":
		#form = UserCreationForm(request.POST)
		if form.is_valid():
			user = form.save()
			username = form.cleaned_data.get('first_name')
			email = form.cleaned_data.get('email')
			login(request,user)
			messages.success(request, f"New account created: {username}")
			newUser=myUser(user_name=username,email=email)
			newUser.save()
			zeroGrp=myGroup.objects.get(group_id=0)
			zeroGrp.users.add(newUser)
			return redirect("dashboard:index")
	#form = UserCreationForm

	return render(request = request,
			template_name = "dashboard/register.html",
			context={"form":form})

def logout_request(request):
	logout(request)
	messages.info(request, "Logged out successfully!")
	return redirect("dashboard:index")

def login_request(request):
	if request.method == 'POST':
		form = AuthenticationForm(request=request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}")
				return redirect('dashboard:index')
			else:
				messages.error(request, "Invalid username or password.")
		else:
			messages.error(request, "Invalid username or password.")
	form = AuthenticationForm()
	return render(request = request,
		template_name = "dashboard/login.html",
		context={"form":form})

#############################################################################################3

def personal_page(request):
	#import pdb; pdb.set_trace()
	global transFormType
	global participants_list
	global title
	global trans_type
	global date
	global group
	global transaction
	user_id=request.user.id
	user=get_object_or_404(myUser, pk=user_id)
	nonfriend=myUser.objects.exclude(friends__in=[user])
	transactions=Transaction.objects.filter(participants__in=[user])
	friend=user.friends.all()
	d=dict()
	for friend1 in friend:
		d[friend1]=0
	for transaction1 in transactions:
		logging.debug('transaction name'+transaction1.title)	
		if transaction1.group_id==0 or transaction1.trans_type=="mintrans":
			tDset=transaction1.transactiondetail_set.all()
			logging.debug('transaction name'+transaction1.title)
			for transdet in tDset:
				messages.info(request,f"{transdet.lent} {transdet.creditor}")
				credit=transdet.creditor
				debit=transdet.debitor
				lent=transdet.lent
				if credit == user:
					if debit in d.keys():
						d[debit]=d[debit]+lent
					else:
						d[debit]=lent
				elif debit == user:
					if credit in d.keys():
						d[credit]=d[credit]-lent
					else :
						d[credit]=(-1*lent)

	dtuple=dict()
	for k,v in d.items():
		dtuple[k]=(v,-v)
	transactionForm=TransactionForm(initial={'transType':'Others','date':datetime.date.today()},user_id=user_id)
	if request.method=="POST":
		logging.debug('post request')
		if 'cancel' in request.POST:
			logging.debug("Cancelling everything")
			transactionForm=TransactionForm(initial={'transType':'Others','date':datetime.date.today()},user_id=user_id)
			transFormType=1
			participants_list=[]
			title="the transaction"
			trans_type="Others"
			date=None
			group=None
			transaction=None
		else:
			if transFormType==1:
				logging.debug('formType=1')
				trForm=TransactionForm(request.POST, user_id=user_id)
				if trForm.is_valid():
					title,trans_type,date,group=handleTransaction(request,trForm)
					transFormType=2
					logging.debug('first form submitted')
					transactionForm=TransactionParticipantsForm(user_id=request.user.id,group_id=group.group_id)
				else:
					transactionForm=TransactionForm(initial={'transType':'Others','date':datetime.date.today()},user_id=user_id)
				
			elif transFormType==2:
				logging.debug('formType=2')
				trForm=TransactionParticipantsForm(request.POST,user_id=request.user.id,group_id=group.group_id)
				logging.debug('submitted the second form')
				#breakpoint()
				#import pdb; pdb.set_trace()
				if trForm.is_valid():
					logging.debug('second form valid')
					participants_list=handleTransactionParticipants(request,trForm)
					transFormType=3
					logging.debug('Here')
					transactionForm=TransactionDetailForm(participants_list=participants_list)
				else:
					transactionForm=TransactionParticipantsForm(user_id=request.user.id,group_id=group.group_id)
			else:
				logging.debug('formType=3')
				trForm=TransactionDetailForm(request.POST,participants_list=participants_list)
				if trForm.is_valid():
					logging.debug('this is valid')
					handleTransactionDetail(request,trForm,title,trans_type,date,group,participants_list)
					transFormType=1
					transactionForm=TransactionForm(initial={'transType':'Others','date':datetime.date.today()},user_id=user_id)
				else:
					logging.debug('this is invalid')
					transactionForm=TransactionDetailForm(participants_list=participants_list)

	return render(request,'dashboard/personal_page.html',{'user':user,"nonfriend":nonfriend, "transForm":transactionForm,"trType":transFormType,'mydict':dtuple});

###############################################################################

def handleTransaction(request,trForm):
	user_id=request.user.id
	#trForm=TransactionForm(request.POST, user_id=user_id)
	#transaction=trForm.save()
	newTransaction=None
	if trForm.is_valid():
		title=trForm.cleaned_data.get('title')
		trans_type=trForm.cleaned_data.get('trans_type')
		date=trForm.cleaned_data.get('date')
		group=trForm.cleaned_data.get('group')
	return (title,trans_type,date,group)

def handleTransactionParticipants(request,trForm):
	#trForm=TransactionParticipantsForm(request.POST,user=myUser.objects.get(request.user.id),group=group)
	participants_list=[]
	if trForm.is_valid():
		part=trForm.cleaned_data.get('participants')
		for participant in part:
			participants_list.append(participant)
		#participants_list.append(myUser.objects.get(pk=request.user.id))
	return participants_list

def handleTransactionDetail(request,trForm,title,trans_type,date,group,participants_list):
	user_id=request.user.id
	ndate=datetime.datetime.combine(date,datetime.datetime.now().time())
	newTransaction=Transaction(title=title,trans_type=trans_type,date=ndate,group=group)
	newTransaction.save()
	for participant in participants_list:
		newTransaction.participants.add(participant)
	newTransaction.save()
	#breakpoint()
	#trForm=TransactionDetailForm(request.POST,participants_list=participants_list)
	if trForm.is_valid():
		gave_extra=[]
		gave_less=[]
		totalshares=0
		totaleq=0
		for participant in participants_list:
			if not trForm.data[str(participant.id)+'share']:
				totaleq=totaleq+1
			else:
				totalshares=totalshares+trForm.cleaned_data.get(str(participant.id)+'share')
		amount=trForm.cleaned_data.get('amount')
		logging.debug(str(amount))
		logging.debug(str(totaleq))
		logging.debug(str(totalshares))
		for participant in participants_list:
			if not trForm.data[str(participant.id)+'share']:
				given=trForm.cleaned_data.get(str(participant.id)+'gave')-((amount-totalshares)/totaleq)
				logging.debug(given)
			else:
				given=trForm.cleaned_data.get(str(participant.id)+'gave')-trForm.cleaned_data.get(str(participant.id)+'share')
			if given>0:
				gave_extra.append([participant,given])
			else:
				gave_less.append([participant,-given])
		gave_extra.sort(key=lambda tup:tup[1],reverse=True)
		gave_less.sort(key=lambda tup:tup[1], reverse=True)

		while len(gave_extra)!=0:
			if gave_extra[0][1]>gave_less[0][1]:
				newTransactionDetail=TransactionDetail(trans=newTransaction,creditor=gave_extra[0][0],debitor=gave_less[0][0],lent=gave_less[0][1])
				newTransactionDetail.save()
				gave_extra[0][1]=gave_extra[0][1]-gave_less[0][1]
				del gave_less[0]
				gave_extra.sort(key=lambda tup:tup[1],reverse=True)
				gave_less.sort(key=lambda tup:tup[1], reverse=True)
			else:
				newTransactionDetail=TransactionDetail(trans=newTransaction,creditor=gave_extra[0][0],debitor=gave_less[0][0],lent=gave_extra[0][1])
				newTransactionDetail.save()
				gave_less[0][1]=gave_less[0][1]-gave_extra[0][1]
				del gave_extra[0]
				if gave_less[0][1]==0:
					del gave_less[0]
				gave_extra.sort(key=lambda tup:tup[1],reverse=True)
				gave_less.sort(key=lambda tup:tup[1], reverse=True)

		if group.group_id!=0:

			#now minimise transactions in the group
			gave_extra=[]
			gave_less=[]

splitwise/dashboard/templates/dashboard/changeMydp.html
{% extends "dashboard/header.html" %}

{% block title %}{{ user.user_name }}{% endblock %}

{% block brand %} 
	<img src ="{{ user.dp.url }}" class="rounded-circle" alt=""width=50 height=50> {{ user.user_name }}{% endblock %}

{% block Profileactive %}active{% endblock %}

{% block content %}
    <div class="container container-table">
        <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button style="background-color:#F4EB16; color:blue" class="btn btn-outline-info" type="submit" value="submit">Update</button>
        </form>
    </div>
{% endblock %}

splitwise/dashboard/templates/dashboard/friend_page.html
{% extends "dashboard/header.html" %}

{% block title %}{{ user.user_name }}{% endblock %}

{% block brand %} 
	<img src ="{{ user.dp.url }}" class="rounded-circle" alt=""width=50 height=50> {{ user.user_name }} and {{friend.user_name}}{% endblock %}

{% block Friendsactive %}active{% endblock %}


{% block content %}
	<a href="{%url 'dashboard:settleup' friend.id%}">
		<button class="btn btn-secondary float-right">SettleUp</button>
	</a>

	{% if state == 'unsettled'%}
		<div class="container">
			<div class="card">
			{%for key,value in mydict.items%}
				{%if key.group_name == 'None'%}
					<div class="card-body">
						<p>Non Group Transactions</p>
						{%if value.0 > 0%}
							<p>You owe Rs. {{value.0}} to {{friend}}</p>
						{% elif value.0 == 0%}
							<p>{{key}} owes you nothing</p>
						{%else%}
							<p>{{key}} owes you Rs. {{value.1}}</p>
						{%endif%}
					</div>
				{%else%}
					<div class="card-body">
						<a href="{% url 'dashboard:group' key.group_id %}"> {{ key.group_name }} </a>
						{%if value.0 > 0%}
							<p>You owe Rs. {{value.0}} to {{friend}}</p>
						{% elif value.0 == 0%}
							<p>{{key}} owes you nothing</p>
						{%else%}
							<p>{{friend}} owes you Rs. {{value.1}}</p>
						{%endif%}
					</div>
				{%endif%}
			{%endfor%}

			</div>
		</div>
	{% else %}
		<div  class="container">
			<br><br><br>
			<p>You are all settled up</p>
		</div>
	{%endif%}

{% endblock %}

splitwise/dashboard/templates/dashboard/header.html
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <!--for bootstrap -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <!---->

  <style type="text/css">
    ul.errorlist{display: none;}
  </style>
</head>
<body>
  <!-- navigation bar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-brand">{% block brand %}{% endblock %}</div>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav">
        <li class="nav-item {% block Friendsactive %}{% endblock %}">
          <a class="nav-link" href="{% url 'dashboard:dashboard' %}">Friends</a>
        </li>
        <li class="nav-item {% block Groupsactive %}{% endblock %}">
          <a class="nav-link" href="{% url 'dashboard:all_groups' %}">Groups</a>
        </li>
        <li class="nav-item {% block Activitiesactive %}{% endblock %}">
          <a class="nav-link" href="{% url 'dashboard:activity' %}">Activities</a>
        </li>
        <li class="nav-item {% block Insightsactive %}{% endblock %}">
          <a class="nav-link" href="{% url 'dashboard:insights' %}">Insights</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="modal" data-target="#exampleModalCenter">Add Transaction</a>
        <li class="nav-item {% block Profileactive %}{% endblock %}">
          <a class="nav-link" href="{% url 'dashboard:user_profile' %}">Profile</a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'dashboard:logout' %}">Logout</a>
        </li>
      </ul>
      </div>
  </nav>

  {% block content %}
  {% endblock %}


  <!-- Modal -->
  <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalCenterTitle">Add an Expense</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form method="post">
          <div class="modal-body" id="formBody">
            {% csrf_token %}
            {{ transForm.as_p }}
          </div>
          <div class="modal-footer">
            <form method="post">
            <button type="submit" class="btn btn-secondary" name="cancel" value="cancel">Cancel</button>
            </form>
            <button id="nxtbtn" type="submit" class="btn btn-primary" value="submitTrans" onclick="nextClick()">Next</button>
          </div>
        </form>
      </div>
    </div>
  </div>

  {% if transForm.errors %}
      {% for field in transForm %}
          {% for error in field.errors %}
              <div class="alert alert-danger alert-dismissible">{{ field.name }}:{{ error|escape }}<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
              </div>
          {% endfor %}
      {% endfor %}
      {% for error in transForm.non_field_errors %}
          <div class="alert alert-danger alert-dismissible">
              {{ error|escape }}<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          </div>
      {% endfor %}
  {% endif %}


  <!--for bootstrap -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <!---->

  <script type="text/javascript">
    //trType=1;
    btn=document.getElementById('nxtbtn');
    form=document.getElementById('formBody');

    
    if({{ trType }}==2)
    {
      //form.show=true;
      $(document).ready(function(){
      // Show the Modal on load
      $("#exampleModalCenter").modal("show");
      });
    }
    if({{ trType }}==3)
    {
      btn.textContent="Done";
      //form.show=true;
      $(document).ready(function(){
      // Show the Modal on load
      $("#exampleModalCenter").modal("show");
      });
    }

    /*function nextClick()
    {
      btn=document.getElementById('nxtbtn');
      form=document.getElementById('formBody');
      if(btn.textContent=="Next")
      {
        form.show="true";
        if({{ trType }}==2)
          btn.textContent="Done";
        //trType+=1;
      }
      else
      {
        btn.textContent="Next";
        //trType=1;
      }
    }*/
  </script>



  

</body>
</html>

splitwise/dashboard/templates/dashboard/pers_group.html
{% extends 'dashboard/header.html' %}

{% block title %}{{ user.user_name }}{% endblock %}

{% block brand %} 
	<img src ="{{ user.dp.url }}" class="rounded-circle" alt=""width=50 height=50> {{ user.user_name }}{% endblock %}

{% block Groupsactive %}active{% endblock %}


{% block content %}

	<div class="container">
		<div class="card">
			{%for key,value in mydict.items%}
				{%if key.group_name != 'None'%}
					<div class="card-body">
						{%if value.0 > 0%}
							<p>You owe Rs.{{value.0}} to 
								<a href="{% url 'dashboard:group' key.group_id %}">{{key.group_name}}</a>
								<a href="{%url 'dashboard:delete' key.group_id %}">
										<button class="btn btn-secondary float-right mr-1">Delete</button>
								</a>
								<a href="{%url 'dashboard:leave' key.group_id%}">
										<button class="btn btn-secondary float-right mr-2">Leave</button>
								</a>
							</p>
						{%elif value.0 == 0%}
							<p>
								<a href="{% url 'dashboard:group' key.group_id %}">{{key.group_name}}</a>
								doesn't owe you anything
								<a href="{%url 'dashboard:delete' key.group_id %}">
										<button class="btn btn-secondary float-right mr-1">Delete</button>
								</a>
								<a href="{%url 'dashboard:leave' key.group_id%}">
										<button class="btn btn-secondary float-right mr-2">Leave</button>
								</a>
							</p>
						{%else%}
							<p>
								<a href="{% url 'dashboard:group' key.group_id %}">{{key.group_name}}</a>
								 owe you Rs. {{value.1}}
								 <a href="{%url 'dashboard:delete' key.group_id %}">
										<button class="btn btn-secondary float-right mr-1">Delete</button>
								</a>
								<a href="{%url 'dashboard:leave' key.group_id%}">
										<button class="btn btn-secondary float-right mr-2">Leave</button>
								</a>
							</p>

						{%endif%}
					</div>
				{%endif%}
			{%endfor%}
		</div>
	</div>


	<div class="container">
		<div id="newGrp" style="margin-top:2%">
		  <div class="card">
			<div class="card-header">
			  <a class="card-link" data-toggle="collapse" href="#grpForm" name="submit">
				Make new Group
			  </a>
			</div>
			<div id="grpForm" class="collapse" data-parent="#newGrp" style="margin-top: 2%; margin-left: 2%;">
			  <form method="post">
			  	{% csrf_token %}
				{{ form.as_p }}
			    <button type="submit" style="background-color:#F4EB16; color:blue" class="btn btn-outline-info" value="submit" name="submit">Done!</button>
			</form>
			</div>
		</div>
	</div>


	

	{% if form.errors %}
      {% for field in form %}
          {% for error in field.errors %}
              <div class="alert alert-danger alert-dismissible">{{ field.name }}:{{ error|escape }}<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
              </div>
          {% endfor %}
      {% endfor %}
      {% for error in form.non_field_errors %}
          <div class="alert alert-danger alert-dismissible">
              {{ error|escape }}<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          </div>
      {% endfor %}
  {% endif %}
	<!--
	<div class="container">
		<div id="newGrp" style="margin-top:2%">
		  <div class="card">
			<div class="card-header">
			  <a class="card-link" data-toggle="collapse" href="#collapseOne">
				Make new Group
			  </a>
			</div>
			<div id="friendList" class="collapse" data-parent="#newGrp">
			  <div class="card-body"style="background-color: #eee;width: 200px;height: 100px;border: 1px dotted black;overflow: scroll;">
					{% for friend in user.friends.all %}
						{% if friend.user_name != "admin" %}
							{% if user.user_name != friend.user_name %}
								<p><a href="{% url 'dashboard:fadd' friend.user_name %}">{{friend}}</a></p>
								<p>{{friend}}</p
							{% endif %}
						{% endif %}
					{% endfor %}
				</div>
			</div>
		</div>
	</div>
-->
{% endblock %}

splitwise/dashboard/templates/dashboard/profile.html
{% extends "dashboard/header.html" %}

{% block title %}{{ user.user_name }}{% endblock %}

{% block brand %} 
	<img src ="{{ user.dp.url }}" class="rounded-circle" alt=""width=50 height=50> {{ user.user_name }}{% endblock %}

{% block Profileactive %}active{% endblock %}


{% block content %}

<div class="container">
    <div class="card">
      <div class="card-body">
          <a href="{%url 'dashboard:changePassword'%}">Change Password</a>
      </div>
      <div class="card-body">
          <a href="{% url 'dashboard:update-pic' %}">Update dp</a>
      </div>
    </div>
{% endblock%}